//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elections.UI.MVC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elections.UI.MVC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryLanguageName parameter is null.
        /// </summary>
        internal static string countrylanguagenamemissing {
            get {
                return ResourceManager.GetString("countrylanguagenamemissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to countryname is null.
        /// </summary>
        internal static string countrynamenull {
            get {
                return ResourceManager.GetString("countrynamenull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languagename paramter is  null.
        /// </summary>
        internal static string languagenamemissing {
            get {
                return ResourceManager.GetString("languagenamemissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roleid is null.
        /// </summary>
        internal static string roleidmissing {
            get {
                return ResourceManager.GetString("roleidmissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rolename is null.
        /// </summary>
        internal static string rolenamenull {
            get {
                return ResourceManager.GetString("rolenamenull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username parameter is null.
        /// </summary>
        internal static string usernamemissing {
            get {
                return ResourceManager.GetString("usernamemissing", resourceCulture);
            }
        }
    }
}
